name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip pre-commit
          pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
