name: Release (PyPI)

on:
  push:
    tags:
      - "v*.*.*"       # e.g., v0.1.0 or v1.0.0
      - "v*.*.*-rc*"   # e.g., v0.1.0-rc1 (pre-release → TestPyPI)

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist_dir: ${{ steps.out.outputs.dist_dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build sdist/wheel
        id: out
        run: |
          python -m pip install --upgrade pip build
          python -m build
          echo "dist_dir=dist" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    if: contains(github.ref, '-rc')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist, path: dist }
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist, path: dist }
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
